# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
bundler_args: --binstubs

# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-1.7.0.preview2
  - ruby-head
matrix:
  allow_failures:
      - rvm: jruby-1.7.0.preview2

script: "bundle exec rake"
