# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
#bundler_args: --binstubs
language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2
  - 2.3.0
  - jruby-9.0.4.0 
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
script: "bundle exec rake"

sudo: false
